### ISSUE TITLE
Issue with AH core service containers and MySQL container

### ISSUE THREAD

**Issue by pettineh** [eclipse-arrowhead/core-java-spring#105]
Version 4.1.3. Master branch. Running docker-compose on Ubuntu 18.10.

I have created the volume for mysql and copied the _create_empty_arrowhead_db.sql_ script to the same directory with the docker-compose file.

Core services are not able to connect to the MySQL server. The compose_mysql_1 service gives following error for each core service: Access denied for user 'core-service-name'@'ip-address' (using password: YES)

It seems to me that the database initialization does not happen on the first run.

**Comment by tsvetlin** [comment]
Hello! 

It does...

You get this error, because yesterday your **compose_mysql_1** container  and volume was already created, when the Image Repository was migrated. It is reusing that volume (without the initialized database, because I added that feature yesterday).

Please execute:
1. `docker-compose down`
2. `docker volume rm mysql`
3. `docker volume create --name=mysql`
4. `docker-compose up -d`

It will work after that.
Best wishes,
Svetlin

**Comment by pettineh** [comment]
Thanks! :)

**Comment by pyXos** [comment]
Hi!

I am getting the same error now. Docker on Mac OS Catalina, tried to setup Arrowhead as described in the readme and also tried the fix mentioned above. All components are up to date. The mysql log states "[Note] Access denied for user 'authorization'@'<IP>' (using password: YES)" for the authorization node (and all other nodes too).

Do you have any idea what I am missing?
Thanks,
Mario

**Comment by Tanjimuddin** [comment]
Hi, I installed arrowhead docker container. I am unable to connect mysql through workbench or terminal either. Can anyone help me to figureout where is the problem?
![Screenshot (291)](https://user-images.githubusercontent.com/44894140/73827096-9cbfae00-4807-11ea-834c-628146b5998c.png)
