### ISSUE TITLE
Docker container Issue and documentation for adding certificate in Linux envt.

### ISSUE THREAD

**Issue by sumi0910** [eclipse-arrowhead/core-java-spring#160]
Hello,

After following the steps mentioned in README to have docker container for Arrowhead framework, I am finding a weird issue with respect all the systems except Service registry and event handler. After a few seconds, the systems stop working. Please have a look at the images for further details.

![image](https://user-images.githubusercontent.com/44111991/70609570-4fa5ce00-1c02-11ea-961c-9fac7a2c1e70.png)

The docker log for Orchestration:
![image](https://user-images.githubusercontent.com/44111991/70609688-867be400-1c02-11ea-975f-4cfca81b2ce3.png)

And it would be really great if there is documentation on adding a certificate to operate in secure mode in the Linux environment as we have for windows OS and as I am completely new to it, having the documentation for it will be helpful. 

Thanks in advance,
Suman

**Comment by tsvetlin** [comment]
Hello!

Documentation will be ready next week.
I'll look into that issue

**Comment by ghost** [comment]
If it were up to me, this issue could be re-opened.

The problem is caused by the `server.address` value in [authorization.properties](https://github.com/arrowhead-f/core-java-spring/blob/master/docker/core_system_config/authorization.properties#L19) containing a trailing space, i.e. "authorization ". This problem is present in other properties files too, but not in [serviceregistry.properties](https://github.com/arrowhead-f/core-java-spring/blob/master/docker/core_system_config/serviceregistry.properties#L19) - in line with @sumi0910 's initial description.

If you manually remove the spaces, the service starts up.

**Comment by sumi0910** [comment]
Hey @selobosi, thanks for the response. I gave up on the Docker container as I didn't have much knowledge of that and installed using Debian packages.

**Comment by ghost** [comment]
Cool! Could you re-open this issue to make sure that the problem in the properties files gets fixed?

Thanks!

**Comment by tsvetlin** [comment]
Guide is ready: https://github.com/arrowhead-f/core-java-spring/pull/182

server.address, server.port, domain.name, domain.port are properly included into the example configuration files.
