### ISSUE TITLE
Flexible Orchestration Store - Orchestration with partial data

### ISSUE THREAD

**Issue by tsvetlin** [eclipse-arrowhead/core-java-spring#209]
When creating orchestration store rules, we have to fill out the following JSON:
```
[
  {
   ....
    "consumerSystemId": 0,
    "providerSystem": {
      "address": "string",
      "authenticationInfo": "string",
      "port": 0,
      "systemName": "string"
    },
    "serviceDefinitionName": "string",
    "serviceInterfaceName": "string",
    ....
  }
]
```
Currently we can't create rules, based on systems that haven't registered themselves, and address and port can change every time a system comes online. It would make sense to provide only the systemName (which is unique and known beforehand) and/or metadata (which would be new). 

Example of the modification:
```
[
   ...
    "consumerSystem": {
      "address": "string", //optional
      "authenticationInfo": "string", //optional
      "port": 0, //optional
      "systemName": "string", // mandatory if metadata not specified otherwise optional
      "metadata": {} // mandatory if systemName not specified otherwise optional
    },
    "providerSystem": {
      "address": "string", //optional
      "authenticationInfo": "string", //optional
      "port": 0, //optional
      "systemName": "string", // mandatory if metadata not specified otherwise optional
      "metadata": {} // mandatory if systemName not specified otherwise optional
    },
    "serviceDefinitionName": "string",
    "serviceInterfaceName": "string",
    ....
  }
]
```

**Comment by jronnberg** [comment]
Since the system registry does not contain metadata (only the service registry does) we will need to somehow connect the metadata in the store rule to the consumer. I see two alternative ways to do this:

    1) extend the system registry with metadata about systems (can be used both for provider and consumer systems). But this requires that all systems register in the system registry even if they do not provide any service. Is this the case today?
    2) extend requesterSystem in the ServiceRequestForm with metadata and match this data to the consumerSystem->metadata in the store rule.


If 1 is selected I think that metadataRequirements in the ServiceRequestForm / ServiceQueryForm should be matched against the union of the metadata in the service registry and the metadata in the systems registry. In my opinion this would give a rely powerful frame work where both systems and service might be identified by metadata.

If 2 i selected consumer systems would not need to register in the system registry, which would give a more light weight consumer system.

A third and perhaps the best option is to do both 1 and 2. The consumer could then either register in the system registry of provide metadata in the ServiceRequestForm.

I think 2 is the option that would require the least changes to the current implementation but option 3 would be the best option in the long run.

**Comment by mzsilak** [comment]
The onboarding controller, device registry and system registry was recently merged with the development branch. Both, the DevicceRegistry and the SystemRegistry contain metadata which could be used in future.

I would extend the authorization rules. There could be multiple devices with the same system (e.g. dozens of sensors of the same type). Usually I would want to allow all devices with the same system to use my service, however there could be cases where only specific devices are allowed to use the service. The current ER model does not reflect this. 

Also having #205 in mind, I am not sure if the IP address should be on the system or on the device. Looking from the other side: If I have dozens of sensors who all have (technically) the same system and expose the same service, I would need to register basically the same system with different IP addresses  and create authorization rules for each of them (multiplied with each consumer). This ought to be easier.

**Comment by jronnberg** [comment]
Marios last comment is also related to these two issues #238 and #237.

**Comment by tsvetlin** [comment]
PDE description document is available for review.

**Comment by rbocsi** [comment]
bump

**Comment by nicnys-8** [comment]
Flexible Orchestration Store Specification:

[flexible-orchestration-spec.pdf](https://github.com/eclipse-arrowhead/core-java-spring/files/6625910/flexible-orchestration-spec.pdf)
