### ISSUE TITLE
Concurrency issue when registering services

### ISSUE THREAD

**Issue by Caranthir** [eclipse-arrowhead/core-java-spring#221]
I want to report the following issue:
I am doing some load/performance tests on Arrowhead framework. For this I send multiple requests at the same time to the Arrowhead FW. When registering services, if you try to register multiple services with the same service_interface, arrowhead tries register them concurrently in the database. Since the service_interface table in the database saves only unique service interface names, it leads to the following error:

`2020-04-07 20:43:18.346  WARN --- [0.0-8443-exec-9] o.h.e.j.s.SqlExceptionHelper             : SQL Error: 1062, SQLState: 23000
2020-04-07 20:43:18.346 ERROR--- [0.0-8443-exec-9] o.h.e.j.s.SqlExceptionHelper             : Duplicate entry 'HTTP-INSECURE-XML' for key 'interface'`

I think that this is a concurrency issue. This error happens even if you send only 3 register requests to the Service Registry component at the same time.

**Comment by borditamas** [comment]
Hello,
issue has been fixed by commit 903196e995ad3c1a3abecdaf5344cd8dbe15a6b6. 
The native SQL created by hibernate is the following from now on regarding the `service_interface` table:

`
    INSERT IGNORE
    INTO
        service_interface(created_at, interface_name, updated_at)
    VALUES
        (?, ?, ?)`

I've have tested locally with 4 concurrent request (with same interface_name) triggered at the same time and all of them has been succeed.

Please run your tests also with the correction and inform us about your results.

**Comment by Caranthir** [comment]
Thanks for the quick fix. I just repeated my tests with the newest version 4.2.0 where your fix was integrated. It has solved the issue.
