### ISSUE TITLE
Orchestration endpoint returns a single provider

### ISSUE THREAD

**Issue by nicnys-8** [eclipse-arrowhead/core-java-spring#237]
This issue regards the _orchestration_ endpoint of the orchestrator.

According to the documentation:
_"if requested service is not specified, then this service returns the top priority local provider of all services contained by the orchestrator store database for the requester system. if requested service is specified, then you have to define the service definition and exactly one interface (all other service requirements are optional). In this case, it returns all accessible providers from the orchestrator store database that provides the specified service via the specified interface to the specified consumer."_

However, even with _requested service_ specified, only a single provider is returned from the orchestrator; the one with the greatest priority.

**Comment by MaGaMeGa** [comment]
At the current state of the orchestrator core system , in case of a store orchestration request, "If requested service is specified ..." then it returns the highest priority provider with valid authorization from the orchestrator store database that provides the specified service via the specified interface to the specified consumer.

To return all providers could be manageable in a store with only local providers, but as soon as foreign providers and the creation of their inter-cloud tunnels cloud be incorporated,
the return of multiple providers is not viable.
 
The current solution is based on the assumption that it is the rule-provider of the orchestration store who make the decision about the consumer-provider rules,
and the priority of the rules with the turn on ping-providers flag would guarantee that the consumer  always supplied with the highest priority available provider.

An alternative solution would be,as in non-store orchestration request -
that inter-cloud orchestration is only available if matchmaking flag is set to true,
and if the matchmaking flag is false, allow the return of multiple local store entries.

**Comment by nicnys-8** [comment]
Okay, thanks for the prompt reply.

We are working on the Plant Description Engine (PDE), which will be another Arrowhead core component.

Our use case:
We want the PDE to continuously check the status of each "monitorable" service that it has access to (via orchestration rules).

Is this impossible when using inter-cloud rules? Again, we want a list containing only the services for which there are rules in the orchestrator.

Perhaps the orchestrator could allow multiple rules to be created with the same priority, and return a _list_ with all highest-priority rules?

**Comment by MaGaMeGa** [comment]
The prioritization is in place to remove the responsibility (of choosing a provider of the same service) off the consumer,
and dedicate it to the rule creator. (The lower priority provider is only orchestrated to the consumer if no higher priority provider is available ...) 
In a scenario where the consumer using orchestration rules to supply multiple provider of the same service would re-dedicate
the responsibility - therefore would be against the whole idea of dedicated rules.

Since the PDE is going to be an other support system and not only a regular consumer, ( it may be the rule creator???)
it is not going to be limited to use the orchestrator store only through orchestration -
it might be allowed to call the orchestration stores endpoints directly.

Please check the orchestration store management endpoints -
https://github.com/arrowhead-f/core-java-spring/blob/master/documentation/orchestrator/ReleaseNotes-4.1.3-Orchestrator.pdf
it has store entities listing capabilities.

Are you looking for similar functionality for the PDE system?

**Comment by nicnys-8** [comment]
Bypassing the orchestration by having the PDE use core system API:s will only solve part of our problems.

We have other use cases where we want the PDE to create rules such that non-core systems will be presented with multiple providers for the same service. For example, one of our demo scenarios is having a "cloud uploader" service that connects to (consumes) an arbitrary number of services providing sensor data.

Allowing multiple local store entries to be returned from the Orchestrator would be our preferred solution.

**Comment by MaGaMeGa** [comment]
Please help me to clarify :

Given you have multiply providers of the same service, and
your CoreSystem (PDE) know which consumer are allowed to consume
from which provider and
your CoreSystem (PDE) able to create authorization rules:

When the rules are created and
the consumer do orchestrates
(regular, non-store orchestration)
for the given service, and
set the enableInterCloud flag to false and
set the matchmaking flag to false and
set the medadataSearch fag to false,

Then the consumer will receive a list of
all the providers for which the consumer has valid authorization rules.

What is the functionality that you would expect from the
orchestration store, and is not listed above?

**Comment by jronnberg** [comment]
As a example assume that we have several sensor systems S1 - S9, they all provide the same service. Further we have a system C that should be connected to some of these sensors but perhaps not all of them.

We create authentication rules such that C is allowed to connect to all sensor systems when setting up the systems since we know that C is allowed to talk to all sensors.

Now we want to populate the Orchestrator with Store rules to decide which sensors C should connect to.
Say that we insert store rules stating the C should connect to S3, S6, and S8.

A goal with the PDE system is to be able to easily switch between different variants of the plant and hence only change the store rules that are affected, for example remove the rule C -> S6 and insert C -> S7.

Since C should not connect to all sensors in the plant, C will have to ask the orchestrator to use the Store rules and not regular orchestration.

One way to support this could be to allow store rules with the same priority and then the Orchstrator returns all entries with the same priority. Another is to return all entries from the Store rules and let the consumer C decide which ones to use, perhaps based on the priority if it is also could be returned (Note that this would only be the case if C askes for that). 

Either way we need the Orchestrator to be able to return several entries even when Store rules are used.

**Comment by tsvetlin** [comment]
PDE description document is available for review.
