### ISSUE TITLE
Changes to Service Registry DB constraints

### ISSUE THREAD

**Issue by nicnys-8** [eclipse-arrowhead/core-java-spring#238]
We suggest a small change to the Service Registry:

It should allow two or more services to share the same _(service_id, system_id)_ pair, as long as their _service_uris_ differ.

This requires changes to the database and the Service Registry code. An implementation suggestion by @aparajita07 can be found [here](https://github.com/aparajita07/core-java-spring/blob/ServiceRegistryChanges/serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java).

In the database table _service_registry_, the unique key `('service_id','system_id')` should be replaced with the tuple `('service_id','system_id','service_uri')`.

**Comment by borditamas** [comment]
Hello, 
in order to have better understanig, could you please describe your requirement more in deatils? Is this because of different protcolls are offered by the same system for the same service definition?

**Comment by aparajita07** [comment]
Hi,

For the implementation of plant description engine, we are using a Fischertechnik factory as an use case which has 9 sensors and 10 actuators. In the arrowhead cloud we are considering this factory as one provider system which can offer two services: sensorvalue (to get the value of each sensor) and actuatorvalue (to get the value of each actuator) where these services will have different service URIs for different sensors and actuators. By using this code, a single system can register multiple instances of the same service id in the service registry with different service Uri.

Thanks & Regards,
Aparajita

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by aparajita07** [comment]
+Looping Nicklas

Thanks & Regards,
Aparajita

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by borditamas** [comment]
Changing the ServiceRegistry unique constraint is absolutely a valid discussion for the coming Arrowhead v5 (along with other aspects as well)

But in your exact case I feel the intention is not really complient with Arrowhead and System of Systems concept. So, you cannot register a provider just in order to register more different provider. A provider is allowed to register only itself (authenticated based on its certificate). Instead of this you have to register all sensor and actuator as individual provider which are offering the same service definitions, but on different addresses. Or, if your intention is only the Fischertechnik system should provide the service definitions, than Fischertechnik should be able to manage and select the requested sensor and actuator based on the consumer request. For example with path parameter (if we are talking about HTTP) like `address:port/sensor_value/{locationId}`. Something like this. 

Probably the second one is what you would need, but I'm not familiar at all with your project.

**Comment by jronnberg** [comment]
You assume that one can change the service definition to support several instances using a path parameter but that is not always the case. 

We have a system that provides several services using a single web server (address:port). Some of these service instances have different Service Definitions (SD) but some of them share the same SD.

I think that the ArrowHead framework should be flexible enough to allow a system to register all the service instances that it provides even if some of them share the same SD as long as there is something (that is the service_uri) that distinguish them.

Why do you think that a system (address:port) should only be allowed to provide one instance of a service with a given SD?

**Comment by borditamas** [comment]
>Why do you think that a system (address:port) should only be allowed to provide one instance of a service with a given SD?

Currently a system can provide multiple services with differnt Service Desription names. Why would you split a system's resources to provide exactly the same serivce in multiple instance, when one instance could use all the the resources? The result would be same or even better with a single instance.

**Comment by jronnberg** [comment]
It is the same service but for different thing, for example, different sensors.

Assuming that you can change the Service Description to allow it to handle several things within the service you could handle it within one service instance. However, if you are stuck with a Service description and corresponding implementation of a service and you are not allowed to change it.... 

If you would still like to provide these service instances using one web server to share resources you still do have to register each service instance for the individual sensors in the service registry.

To handle this today you have to register the same service with different service description names. Then you force the consumer of the service to be aware of the exact instances that it should connect to (since it needs to be part of the service definition name) not only the type of service. In my opinion the consumer should not have to be aware of that since it is the job of the Orchestrator (actually the operator that creates Orchestration Store Rules and Authorization rules) to know which providers each consumer should connect to.

**Comment by jenseliasson** [comment]
We at ThingWave have identified exactly the same issue. We have developed a new AH system called BorderGateway that exposes our low power wireless IoT devices as services. 

So 10 wireless devices with a temperature sensor will be exposed as 10 temperature services provided by the BorderGateway system which runs on our gateway platform. If a wireless devices disconnects, we will unregister the corresponding service to make it unavailable for consumers.

We also have the case when one provider has several sensors physical connected to it. In this case we want to treat each physical sensor as s service, provided by the system provider.

So running everything as one service instance causes a lot of issues. 

And I also believe that the framework should not impose restrictions unless absolutely necessary.

**Comment by emanuelpalm** [comment]
Not all possible communication protocols rely on URIs, which means that the `sericeUri` field becomes practically useless when using a protocol such as AMPQ, unless the field is abused and contains something that is not a URI (such as a topic specifier). One possibility would be to rename the table column to something more generic, such as `qualifier`, and just assume that each possible protocol has a well-defined way of using that qualifier.

Personally, I thought the whole point of the `serviceUri` was to help separate services served by the same system over the same port. I'm still, however, not quite sure I understand the real intent of the `serviceUri`.

**Comment by tsvetlin** [comment]
PDE description document is available for review.

**Comment by emanuelpalm** [comment]
@tsvetlin Where can I read it? :)

**Comment by rbocsi** [comment]
bump
