### ISSUE TITLE
Why does initSQL.sh fetch files via network?

### ISSUE THREAD

**Issue by wentasah** [eclipse-arrowhead/core-java-spring#343]
I'm confused. [README](https://github.com/eclipse-arrowhead/core-java-spring#docker) says to copy initSQL.sh from the `/scripts` directory to `/docker`. The script copies the `*.sql` files from the "same" directory but from the current version on github rather than from the local copy. Interestingly enough, the [initSQL.sh from eclipse-arrowhead](https://github.com/eclipse-arrowhead/core-java-spring/blob/7c280383af4df638841188b48dd3f008ff6487b4/scripts/initSQL.sh) copies the files from `arrowhead-f` github repo and the [initSQL.sh from arrowhead-f](https://github.com/arrowhead-f/core-java-spring/blob/db9af0291f2aedfcce3a20087892d3609bc705b7/scripts/initSQL.sh) copies from `eclipse-arrowhead`. This seems extremely weird and likely to lead to many inconsistencies.

I'd suggest to change the `initSQL.sh` script to always copy the files from the locally cloned repository to ensure consistency with the currently checked out version.

**Comment by tsvetlin** [comment]
Hello!

The arrowhead-f/core-java-spring repository contains the latest 4.4.0 release, and is in the process of being merged back here, thats why it is pointing to the updated location of the sql files.

Moreover, this script allows to be ran in a standalone mode, thats why it's getting the scripts from the repository. You do not need to check out the whole repository this was.

If you wish, you can create a `initSQL-local-copy.sh` for this purpose and create a PR, otherwise the purpose of this script is to be run in a standalone mode.

**Comment by wentasah** [comment]
Thanks for the explanation. It would be nice if standalone mode is also documented in the README. Where shall be the PRs sent? This repo, develoment branch or arrowhead-f repo?

**Comment by tsvetlin** [comment]
If you are an Eclipse comitter then this repo. Else the arrowhead-f.
