### ISSUE TITLE
IntelliJ project configuration files

### ISSUE THREAD

**Issue by tsvetlin** [eclipse-arrowhead/core-java-spring#55]
I suppose that many developers are using IntelliJ to work on Arrowhead. In the old core-java package, we had the configuration/project files for IntelliJ and people were able to code and execute the code without losing time ( = creating a IntelliJ project, configuring it, etc).
 
Do you consider to add IntelliJ-related files in the new core-java-spring package repository?
 
Best,
Michele

**Comment by eudyptula** [comment]
To put this into context, several surveys conclude that IntelliJ IDEA is the most popular IDE for Java development, e.g.:
- [Java 2019 - The state of Developer Ecosystem in 2019 Infographic](https://www.jetbrains.com/lp/devecosystem-2019/java/):
   65% uses IntelliJ IDEA over 17% using Eclipse (I admit this might be a bit biased)
- [Stack Overflow Developer Survey 2019](https://insights.stackoverflow.com/survey/2019#development-environments-and-tools):
   25.4% for IntelliJ and 14.4% for Eclipse overall.
- [Largest Java Developer Survey 2018](https://programmer9.com/2019/02/06/largest-java-survey-2018.html):
   45% uses IntelliJ IDEA over 38% using Eclipse.
- Not to mention that the official IDE for Android has switched from Eclipse to IntelliJ...

The intended purpose of these files was to facilitate a clone-and-play concept where Arrowhead could be built and run straight out of the box within the IDE, significantly lowering the entry barriers for new Arrowhead adopters and developers. Furthermore, they helped ensure a common code style among all developers, avoiding commits with changing indentations etc.

Furthermore IntelliJ IDEA have been supported by Arrowhead in the pre-spring versions since 2018, maintained by both @uzoltan and myself ([Commit history](https://github.com/arrowhead-f/core-java/commits/develop/.idea)). I see no reason why we should move backwards in supporting this feature. 

For consistency across developers, the corresponding project files for other popular IDEs (Eclipse, etc.) could profitably be added also.

Personally, I have not tried the new spring version of Arrowhead, nor will I have the time for it within the time I have left on the project.

**Comment by tsvetlin** [comment]
If anybody would like to do it, just reopen this issue.
