### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by vanDeventer** [eclipse-arrowhead/core-java-spring#7]
Hi,

Would you please add a README.md so that one can understand what "Spring" is all about?

Thank you.

**Comment by tsvetlin** [comment]
Hello!

Spring is a framework. See more at: [https://spring.io/](url)
We are refactoring the Arrowhead Core Systems, because the current implementation has multiple bugs, design flaws. We will provide documentation in time, until we are finished, please use the original implementation. 

If you have any more questions, feel free to ask!

Kind regards,
Svetlin
