### ISSUE TITLE
Issue during deployment of the Service Registry system

### ISSUE THREAD

**Issue by sumi0910** [eclipse-arrowhead/core-java-spring#91]
<img width="925" alt="service_registry_issue" src="https://user-images.githubusercontent.com/44111991/66308925-93314280-e908-11e9-9fb4-75813fff89fc.PNG">

On executing java -jar arrowhead-serviceregistry-4.1.3.jar , the framework after starting ServiceRegistryMain and on waiting of 60 min also, nothing seems to work and have to kill the process.

**Comment by tsvetlin** [comment]
Hello!

In the screenshot you provided. I can see that you started the core system in SECURE mode (which is the default). And it started in 54s.

After that it is available on `https://localhost:8443`. Since it is started in secure mode, you need to use the certificate to access it. Please refer to this issue: [https://github.com/arrowhead-f/core-java-spring/issues/79](https://github.com/arrowhead-f/core-java-spring/issues/79)

Best wishes,
Svetlin

**Comment by tsvetlin** [comment]
Hello! 
Any updates on that?

**Comment by sumi0910** [comment]
I switched back to 4.1.2 version as i am developing the application in c++ so. Hopefully, u can close this issue I think.
